### PR TITLE
Make distribution friendly: install and read femto.rc and lisp extens…

### PR DESCRIPTION
**Pull request by jorge-leon**
…ions

femto reads `femto.rc` from `E_INITFILE`, which now defaults to `/usr/local/share/femto/femto.rc` but can be overridden via `CPPFLAGS`.

`femto.rc` is generated from `femto.rc.in` so the lisp extension directory can be defined at compile time. It has been refactored, so that it only defuns required functions, others have been moved to `femto.lsp` as basic femto extensions.

The examples directory is renamed to `lisp` to reflect the requirement to install the contained files.

README has been updated and also contains instructions on building for running in the current working directory.

### CODE REVIEW

**Comment by hughbarney** [comment]
I have pulled your code into a branch for test.
To build it I did

$ cd ~/src/femto
$ sudo make install
...


cpp -P -D SCRIPTDIR=/usr/local/share/femto femto.rc.in femto.rc
cc  -o femto command.o display.o complete.o data.o gap.o key.o search.o buffer.o replace.o window.o undo.o funcmap.o utils.o hilite.o lisp.o main.o -lncursesw
mkdir -p $DESTDIR/usr/local/bin
cp femto $DESTDIR/usr/local/bin
mkdir -p $DESTDIR/usr/local/share/femto
cp lisp/*.lsp femto.rc $DESTDIR/usr/local/share/femto


$ which femto
/usr/local/bin/femto

## this looks good

 
$ pwd
/home/hugh/src/femto
 
$ femto


femto 2.12:
error: /usr/local/share/femto has no value

# not sure what happened here ?


$ pwd
/home/hugh/src/femto

$ ls /usr/local/share
ca-certificates  emacs  femto  fonts  man

$ ls /usr/local/share/femto/
bufmenu.lsp  defmacro.lsp  dired.lsp  femto.lsp  femto.rc  fib.lsp  git.lsp  grep.lsp  hex.lsp  lists.lsp  oxo.lsp  prompt.lsp  startup.lsp  testfunc.lsp

Files are there.

**Comment by hughbarney** [comment]
ok, the problem is that $HOME/.config/femto is not created my `sudo make install`

**Comment by jorge-leon** [comment]
The problem is a missing quoting in `makefile`.  You can find the line in this commit: [ #da8e3d9](https://github.com/jorge-leon/femto/commit/da8e3d9edebb21f337e7f7b90a4dffc9706afa1f).

Sorry, I managed to put it in the wrong branch.

**Comment by jorge-leon** [comment]
It's cherry picked to the right branch,you should be able to get it with git pull.

**Comment by hughbarney** [comment]
I'm not sure thats the problem.

That will create /usr/local/share/femto but not $HOME/.config/femto
Where $HOME in this context is the home dir of the user who compiles it.

To reproduce what I am seeing
Do a make clean
Then rmdir -rf $HOME/.config/femto

Then
sudo make install

Then try and start up femto
You will see that it fails as the path $HOME/.config/femto does not exist
after sudo make install has been run

I suspect we will need a new lisp built in path_exists, and maybe file_exists so that the master femto,rc
can check for the existance of a local femto.rc file before attempting to load it.

**Comment by jorge-leon** [comment]
It's working on my side - using the "Fix: add missing quotes for script dir" commit.

I know that the master `femto.rc` tries to load `$HOME/.config/femto/femto.rc`, but if it fails it just goes on. I made it in a way, that it is optional to have a users `femto.rc`.  I added a section "Femto Startup" to the README.md file with a terse description of the process.

The error message you copied in the previous comment is not related to the look up of the users `femto.rc`.

----
The users femto.rc should not be created by `make install`. On Linux you run `make install ` as root, and you do not want to modify any users $HOME directory.  This would be a task of the program itself.  In fact on could createit from within the global `femto.rc` itself via `(shell-command ..)`, but I advice against it.

**Comment by hughbarney** [comment]
Ok - this has been fully merged in. 
I also fixed the duplicate startup code and added the end-of-buufer to the end of start up.

**Comment by hughbarney** [comment]
Ok - this has been fully merged in.  Please do a pull.
I also fixed the duplicate startup code and added the end-of-buufer to the end of start up.

**Pull request closed without merging**
